### ISSUE TITLE
ApiException for TransactionSplit no attribute 'external_uri'

### ISSUE THREAD

**Issue by chrgm** [ms32035/firefly-iii-client#10]
When I run the example code, besides from the `dateutil_parser` which I needed to import and change to `parser.parse`. I always get an `ApiException` for the `TransactionSplit` model. It doesn't matter if I want to store a transaction or get them. 

This is the error I get when I just use the [example](https://github.com/ms32035/firefly-iii-client/blob/master/docs/TransactionsApi.md#store_transaction) code but also every other code.
```
firefly_iii_client.exceptions.ApiAttributeError: TransactionSplit has no attribute 'external_uri' at ['received_data']['data'][0]['attributes']['transactions'][0]['external_uri']
```
It seems to be that `external_uri` is not defined but the server sends it back which leads to the exception.
May somebody be able to change that or show me my mistake?

**Comment by ms32035** [comment]
this looks like an issue with the specification - https://api-docs.firefly-iii.org/

**Comment by ms32035** [comment]
Check latest version (1.5.4), and report again if still an issue, and not a specification problem
