### ISSUE TITLE
Private Firefly instance with self signed ssl certificate

### ISSUE THREAD

**Issue by a-waider** [ms32035/firefly-iii-client#11]
Hi,
I'm using a private instance of Firefly behind a https proxy. This proxy has a custom CA which need to be manually installed on the os. Now it doesn't seem to work with python so I was wondering if there is a config for disabling the certificate check in the api client.

**Comment by ms32035** [comment]
This looks like a question to the openapi team if they want to implement the feature in the code generator

**Comment by a-waider** [comment]
After advanced search I found this setting: https://github.com/ms32035/firefly-iii-client/blob/master/firefly_iii_client/configuration.py#L155
