### ISSUE TITLE
'dateutil_parser' is not defined

### ISSUE THREAD

**Issue by delcooper11** [ms32035/firefly-iii-client#16]
I copied the example from [here](https://github.com/ms32035/firefly-iii-client/blob/master/docs/AccountsApi.md#list_transaction_by_account) exactly as-is and got a NameError.

> Traceback (most recent call last):
>   File "/Users/danielcooper/Developer/ListTransactionsByAccount.py", line 31, in <module>
>     start = dateutil_parser('Mon Sep 17 00:00:00 UTC 2018').date() # date | A date formatted YYYY-MM-DD.  (optional)
>             ^^^^^^^^^^^^^^^
> NameError: name 'dateutil_parser' is not defined

I was able to resolve this by adding 
`from dateutil.parser import parse as dateutil_parser` after line 1

**Comment by ms32035** [comment]
@delcooper11 I regenerated with the latest openapi-generator and also changed the project for easier setting of versions in the docker-compose file, but unfortunately the error is coming from here https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonPriorClientCodegen.java so might want to raise an issue in the openapi-generator project
