### ISSUE TITLE
Access Token is set to None in Configuration

### ISSUE THREAD

**Issue by mukundv** [ms32035/firefly-iii-client#19]
https://github.com/ms32035/firefly-iii-client/blob/379f88b8d9b3fa0d5819fa26004fc97c39319b3d/firefly_iii_client/configuration.py#L114
Not an expert, but this line is causing authentication to fail. 
Shouldn't this be `self.access_token = access_token`

**Comment by daviterri** [comment]
Yes, I was having trouble with the authentication, this fixed it

> https://github.com/ms32035/firefly-iii-client/blob/379f88b8d9b3fa0d5819fa26004fc97c39319b3d/firefly_iii_client/configuration.py#L114
> 
> 
> Not an expert, but this line is causing authentication to fail.
> Shouldn't this be `self.access_token = access_token`

**Comment by soloam** [comment]
I also noticed this! What is the reason to have this set to none? Can't we use the api with token?

**Comment by ms32035** [comment]
@soloam the reason was a bug in the openapi generator, which they now fixed. Please try release 2.0.12.0
