### ISSUE TITLE
import Configuration defined twice in __init__.py

### ISSUE THREAD

**Issue by zhuqf** [ms32035/firefly-iii-client#7]
because of this 
`configuration = firefly_iii_client.Configuration(host = "https://demo.firefly-iii.org")`
would not work, it only work with 
`configuration` = firefly_iii_client.configuration.Configuration(host = "https://demo.firefly-iii.org")`

**Comment by ms32035** [comment]
Right, name clash between OpenApi objects and Firefly-III models. The code is autogenerated and as such I try to not modify it, but I'll see if there's anything I can do next time I generate it for a new version

**Comment by ms32035** [comment]
If still an issue, feel free to submit a PR here https://github.com/ms32035/firefly-iii-client/blob/master/.generator/postprocess.py
