### ISSUE TITLE
Pip install command not working

### ISSUE THREAD

**Issue by gabrielecalvo** [ms32035/firefly-iii-client#9]
I believe it's supposed to say:
"pip install Firefly-III-API-Client"
instead of 
"pip install firefly-iii-client"

**Comment by ms32035** [comment]
I have regenerated and republished the package with the latest generator for API version 1.5.2, but what you are raising is coming from the autogenerated code, so should be raised with the OpenAPI project, unless pip behaviour changed between versions and it's a pip issue

**Comment by Findus23** [comment]
I also think the docs are wrong here.

The package is called `Firefly-III-API-Client` (see https://pypi.org/project/Firefly-III-API-Client/) and not `firefly-iii-client` (https://pypi.org/project/firefly-iii-client/), so the mentioned pip install can't work.
